### ISSUE TITLE
Support for Logitech H800 headset buttons?

### ISSUE THREAD

**Issue by TinaRussell** [lonelobo0070/MusicBee-Logitech-applet#1]
This is a feature request. I know this plugin is meant to support Logitech gaming keyboard thingies, but I have a Logitech H800 headset with media buttons which I was devastated to find out are proprietary and only Windows Media Player and iTunes are supported (via Logitech-made plugins)—surely they could have just emulated the standard media keys?! …Anyway.

http://support.logitech.com/en_us/product/wireless-headset-h800 (“Downloads” contains the WMP/iTunes plugin, under “Track Control Software,” while the first heading in the FAQ is where Logitech admits they only thought to support WMP and iTunes.)

I’m hoping, perhaps this plugin could be extended to make use of the H800’s (or similar headsets’) media buttons? I suppose that would depend on whether Logitech’s keypads and headsets have similar idiosyncrasies. I wouldn’t know, though.

**Comment by jimmyd-be** [comment]
I cannot promise anything about adding support for the H800 to Musicbee. If I can found some SDK from Logitech himself it is possible to include it in the plugin. Otherwise I need to find another way (if it is possible).

**Comment by jimmyd-be** [comment]
Did you already tried 'Wireless Headset H800 Media Track Control Software'? Normally media keys are default keys in Windows and probably they are working on MusicBee.

**Comment by TinaRussell** [comment]
Yep, I did. The Media Track Control Software thingy is a plugin for iTunes and Windows Media Player—it does not emulate the standard Windows media keys (argh, Logitech, why?!)

**Comment by jimmyd-be** [comment]
Out of scope for this project.
The initial project is to view the data on Logitech Keyboards.
