### ISSUE TITLE
Not working on Logitech G15 with Musicbee v3.3.7115

### ISSUE THREAD

**Issue by tachmonite37** [lonelobo0070/MusicBee-Logitech-applet#2]
I have added the 3 DLLs to the MusicBee Plugins folder but on the G15 display it only displays 'MusiBee'. It doesn't display the track title etc.

Am I missing something? Please assist.

Thanks in advance.

**Comment by jimmyd-be** [comment]
Sorry for the late response. I was on vacation.
It looks like you did not configured the plugin. You can do that by opening settings -> Plug-ins -> configure. You should at least 1 page in the right page column. Let me know if this fixed the issue?

![musicbee_settings](https://user-images.githubusercontent.com/34766203/62422075-ec80b980-b6ac-11e9-992f-74ec3c6ba7c3.png)

**Comment by jimmyd-be** [comment]
No response. Looks like it is fixed
